apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    a: b
  name: nginx
  namespace: nginx-ns
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx

