apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    #argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "4"
  namespace: nginx-ns
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "3"]
      restartPolicy: Never
  backoffLimit: 0