apiVersion: v1
kind: Namespace
metadata:
  annotations:
    
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
    argocd.argoproj.io/sync-options: Prune=false
  name: nginx-ns

